[package]
name = "exchange"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_decimal = "1.14.1"
thiserror = "1.0.25"
serde = { version = "1.0", features = ["derive"] }
